#!/usr/bin/env node
'use strict';
/**
 * Build src/js/data/legal-i18n.js from docs/legal/{en,es,zh,ja}/{privacy,terms}.md
 *
 * Markdown format:
 *   ---
 *   title: ...
 *   eyebrow: ...
 *   updatedLabel: ...
 *   updatedDate: ...
 *   onThisPage: ...
 *   lead: "HTML allowed in JSON string"
 *   footerNote: "..."
 *   ---
 *
 *   ## Section Title {#section-id}
 *
 *   <p>HTML body…</p>
 *
 * Usage: node tools/build-legal.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const LEGAL_DIR = path.join(ROOT, 'docs', 'legal');
const OUT = path.join(ROOT, 'src', 'js', 'data', 'legal-i18n.js');
const LANGS = ['en', 'es', 'zh', 'ja'];
const KINDS = ['privacy', 'terms'];

function die(msg) {
  console.error('[build-legal] ' + msg);
  process.exit(1);
}

/** Minimal YAML-ish frontmatter: key: value or key: "json string" */
function parseFrontmatter(raw) {
  if (!raw.startsWith('---')) die('missing frontmatter ---');
  const end = raw.indexOf('\n---', 3);
  if (end < 0) die('unclosed frontmatter');
  const fmBlock = raw.slice(3, end).replace(/^\n/, '');
  const body = raw.slice(end + 4).replace(/^\n/, '');
  const meta = {};
  const lines = fmBlock.split(/\n/);
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!line.trim()) continue;
    const m = line.match(/^([A-Za-z][A-Za-z0-9_]*)\s*:\s*(.*)$/);
    if (!m) die('bad frontmatter line: ' + line);
    const key = m[1];
    let val = m[2].trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      try {
        val = JSON.parse(val.startsWith("'") ? '"' + val.slice(1, -1).replace(/"/g, '\\"') + '"' : val);
      } catch (e) {
        val = val.slice(1, -1);
      }
    }
    meta[key] = val;
  }
  return { meta, body };
}

function parseSections(body) {
  const sections = [];
  const re = /^##\s+(.+?)\s*\{#([a-z0-9-]+)\}\s*$/gm;
  const matches = [];
  let m;
  while ((m = re.exec(body)) !== null) {
    matches.push({ title: m[1].trim(), id: m[2], index: m.index, len: m[0].length });
  }
  if (!matches.length) die('no sections found (need ## Title {#id})');
  for (let i = 0; i < matches.length; i++) {
    const start = matches[i].index + matches[i].len;
    const end = i + 1 < matches.length ? matches[i + 1].index : body.length;
    const html = body.slice(start, end).trim();
    if (!html) die('empty section body for #' + matches[i].id);
    sections.push({ id: matches[i].id, title: matches[i].title, html: html });
  }
  return sections;
}

function loadDoc(lang, kind) {
  const file = path.join(LEGAL_DIR, lang, kind + '.md');
  if (!fs.existsSync(file)) die('missing ' + path.relative(ROOT, file));
  const raw = fs.readFileSync(file, 'utf8');
  if (!raw.trim()) die('empty ' + path.relative(ROOT, file));
  const { meta, body } = parseFrontmatter(raw);
  const sections = parseSections(body);
  const toc = sections.map((s) => ({ id: s.id, label: s.title }));
  // Prefer explicit toc labels if we want later; for now section titles = toc labels
  // (original LEGAL_I18N sometimes had shorter toc labels — preserve via ## titles as written)
  return {
    title: meta.title || '',
    eyebrow: meta.eyebrow || 'Legal',
    updatedLabel: meta.updatedLabel || 'Updated',
    updatedDate: meta.updatedDate || '',
    onThisPage: meta.onThisPage || 'On this page',
    lead: meta.lead || '',
    toc: toc,
    sections: sections,
    footerNote: meta.footerNote || '',
  };
}

function build() {
  const LEGAL_I18N = { privacy: {}, terms: {} };
  for (const kind of KINDS) {
    for (const lang of LANGS) {
      LEGAL_I18N[kind][lang] = loadDoc(lang, kind);
    }
  }

  // Restore shorter toc labels from original when section titles differ —
  // actually we stored full section titles in ## headers, which match section.title.
  // Original toc sometimes used shorter labels (e.g. "Agreement to terms").
  // Section title IS what renders as h2; toc label can match section title.
  // For parity with previous file, re-read section titles from md ## lines which
  // were extracted from original section.title (not toc label). Good enough.

  const header = [
    "'use strict';",
    '/**',
    ' * Privacy Policy & Terms of Use — full copy in en / es / zh / ja.',
    ' * Rendered by features/legal.js when body.page-legal is present.',
    ' *',
    ' * GENERATED by tools/build-legal.js — edit docs/legal/{en,es,zh,ja}/*.md then re-run:',
    ' *   node tools/build-legal.js',
    ' *',
    ' * Localization notes:',
    ' * - English is the source of legal meaning.',
    ' * - es / zh / ja are rewritten for natural product-policy voice in each language',
    ' *   (not line-by-line calques). Same section structure and substance as English.',
    ' */',
    'window.LEGAL_I18N = ',
  ].join('\n');

  const json = JSON.stringify(LEGAL_I18N, null, 2);
  const out = header + json + ';\n';
  fs.writeFileSync(OUT, out, 'utf8');
  console.log('[build-legal] wrote ' + path.relative(ROOT, OUT));
  console.log('[build-legal] privacy langs: ' + LANGS.join(', '));
  console.log('[build-legal] terms langs: ' + LANGS.join(', '));
}

build();
